# Working with .csv files

## 1. Importing pandas

In [2]:
import pandas as pd
import numpy as np

## 2. Opening a local csv file
To read CSV file using pandas, use `read_csv` function.

The dataset is taken from Kaggle and has the following 14 features. Its objective is to predict job switch for data scientists...

    - enrollee_id: Unique ID for each candidate.
    - city: Code representing the candidate's city.
    - city_development_index: Scaled socio-economic index of the city.
    - gender: Gender of the candidate.
    - relevent_experience: Indicates if the candidate has relevant work experience.
    - enrolled_university: Type of university course enrolled in, if any.
    - education_level: Highest attained level of education.
    - major_discipline: Primary field of study (e.g., STEM, Humanities).
    - experience: Total years of professional experience.
    - company_size: Number of employees in the current company.
    - company_type: Type of current employer (e.g., Startup, Pvt Ltd).
    - last_new_job: Difference in years between the previous and current job.
    - training_hours: Total hours of completed training.
    - target: Flag showing if a candidate is looking for a job change.

In [16]:
# df = pd.read_csv('aug_train.csv')
# df

In [17]:
# df.shape

In [18]:
# df.info()

In [19]:
# type(df)
# df.columns
# df.index

- Common Pandas data types include `integer, floating point, boolean, string/object, categorical`, and `datetime`.
  - determine how data is stored, processed, and optimized in memory.
- Storage type is not the same as measurement scale. A nominal variable coded as 1, 2, and 3 is still nominal even though Pandas stores it numerically.


| Data Type | Pandas Dtype String | Python/NumPy Equivalent | Best Used For |
| :--- | :--- | :--- | :--- |
| **Integer** | `'int64'` or `'Int64'` | `int` | Whole numbers (e.g., age, counts, IDs). |
| **Float** | `'float64'` | `float` | Fractional numbers, measurements, and percentages. |
| **String / Text** | `'object'` or `'string'` | `str` | Textual data, mixed types, or unparsed values. |
| **Boolean** | `'bool'` or `'boolean'` | `bool` | True/False flags and binary indicators. |
| **DateTime** | `'datetime64[ns]'` | `datetime.datetime` | Timestamps, calendar dates, and time-series markers. |
| **Timedelta** | `'timedelta64[ns]'` | `datetime.timedelta` | Differences between two times (e.g., duration). |
| **Category** | `'category'` | *None* | Repeated text fields with fixed categories (e.g., gender, states). |

In [20]:
# df.dtypes

In [21]:
# df['enrollee_id'] = df['enrollee_id'].astype('string');
# df.dtypes

In [22]:
# df.head()

In [23]:
# df.tail()

In [24]:
# df.sample(5, random_state=42)

## 3. Opening a csv file from an URL

In [25]:
## Alternate way to read csv files from the web
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

Important arguments include `sep`, `header`, `index_col`,
`usecols`, `na_values`, and `parse_dates`.

## 4. Sep Parameter

1. default in CSV file is `comma` , character for field separation
2. we can change it could to characters like `tab` \t, `space ` | … etc.

In [3]:

# # ## raw data gives parser error
# # #url='https://www.kaggle.com/code/gcachemoney/topic-modelling-of-movie-dialogue/data?select=movie_titles_metadata.tsv'
# # #url='https://www.kaggle.com/datasets/Cornell-University/movie-dialog-corpus?select=movie_titles_metadata.tsv'
# # movie='/content/drive/MyDrive/Colab Notebooks/data/movie_titles_metadata.tsv'
# # pd.read_csv(movie) #default separator is ,

movie = 'movie_titles_metadata.tsv'
pd.read_csv(movie, sep='\t')

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [27]:
# changing the default separator to `tab`

pd.read_csv(movie,sep='\t')

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [28]:
## assigning column names/header

pd.read_csv(movie,sep='\t',names=['sno','name','release_year','rating','votes','genres'])

,sno,name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

## 5. Index_col parameter

In [30]:
# df

In [ ]:
#  ## Set a single column as Index:

# df.set_index('enrollee_id')

In [ ]:
#Alternate way from the csv file
#pd.read_csv('aug_train.csv_col='enrollee_id')

## 6. Header parameter

1. `header=0`-- first row of the CSV file will be treated as `column names`.
2. `header=1`-- second row of the CSV file will be treated as `column names`.
3. `header=None`-- CSV file has no header

In [ ]:
pd.read_csv('test.csv')

In [ ]:
pd.read_csv('test.csv',header=1)

## 7. use_cols parameter
 1. use `columns` which are required for your analysis

In [ ]:

pd.read_csv('aug_train.csv')

In [ ]:
pd.read_csv('aug_train.csv',usecols=['enrollee_id','gender','education_level'])

## 8. Squeeze parameters
1. Makes `dataframe` into `series`

In [ ]:

pd.read_csv('aug_train.csv',usecols=['gender'],squeeze=True)

In [ ]:
#df
df.squeeze()

## 9. Skiprows/nrows Parameter

1. `skiprows` skips the particular rows from the output

    i. Skip One Specific Row `skiprows=[2]`      
    ii. Skip Several Specific Rows `skiprows=[2,4]`      
    iii. Skip First N Rows `skiprows=N`
    
    
2. `nrows=10` shows only the first 10 rows

In [ ]:
pd.read_csv('aug_train.csv',nrows=10)

In [ ]:
## show first three rows

pd.read_csv('aug_train.csv',nrows=3)

## skip 2nd row

pd.read_csv('aug_train.csv',skiprows=[2])

In [ ]:
## show first three rows

pd.read_csv('aug_train.csv',nrows=5)

## skip 2nd & 4th rows

pd.read_csv('aug_train.csv',skiprows=[2, 4])

In [ ]:
## show first three rows

pd.read_csv('aug_train.csv',nrows=3)

## skip first two rows

pd.read_csv('aug_train.csv',skiprows=2)

## 10. Encoding parameter

1. all characters are stored in computers using a special code
2. A character encoding provides a key to unlock the code.
3. It is a set of mappings between the `bytes` in the computer and the `characters` in the character set.
4. Without the key, the data looks like garbage.
5. when you input text using a keyboard or in some other way, the `character encoding` maps characters you choose to specific bytes in computer memory, and then to display the text it reads the bytes back into characters.
6. Unfortunately, there are many different character sets and character encodings
7. `UTF-8` is a variable-length character encoding standard used for electronic communication
8. encoding different from `utf8` will result in Unicode error
9. Trace the encoding using an online code editor

In [ ]:
pd.read_csv('./data/zomato.csv')

In [ ]:
# helpful modules
import fuzzywuzzy
from fuzzywuzzy import process
import chardet

# set seed for reproducibility
np.random.seed(0)
# look at the first ten thousand bytes to guess the character encoding
with open("zomato.csv", 'rb') as rawdata:
    result = chardet.detect(rawdata.read(100000))

# check what the character encoding might be
print(result)
#pd.read_csv('zomato.csv',encoding='latin-1')

## 11. Skip bad lines

1. helpful when you get Parser error

In [ ]:
pd.read_csv('BX-Books.csv')

In [ ]:
pd.read_csv('BX-Books.csv', sep=';')

In [ ]:
pd.read_csv('BX-Books.csv', sep=';',error_bad_lines=False)

## 12. dtypes parameter

1. to convert/correct data types

In [ ]:
pd.read_csv('aug_train.csv')

In [ ]:
pd.read_csv('aug_train.csv').info()

In [ ]:
pd.read_csv('aug_train.csv',dtype={'target':int}).info()
#pd.read_csv('aug_train.csv',dtype={'target':np.int64}).info()

## 13. Handling Dates

In [ ]:
pd.read_csv('IPL Matches 2008-2020.csv')

In [ ]:
pd.read_csv('IPL Matches 2008-2020.csv').info()

In [ ]:
pd.read_csv('IPL Matches 2008-2020.csv',parse_dates=['date']).info()

## 14. Convertors

1. to manipulate the values of the column

In [ ]:
pd.read_csv('IPL Matches 2008-2020.csv',parse_dates=['date'])

In [ ]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    elif name == "Kolkata Knight Riders":
        return "KKR"
    elif name == "Chennai Super Kings":
        return "CSK"
    else:
        return name

In [ ]:
rename("Royal Challengers Bangalore")

In [ ]:

pd.read_csv('IPL Matches 2008-2020.csv',converters={'team1':rename, 'team2':rename, 'toss_winner':rename,'winner':rename})


## 15. na_values parameter

1. assign irregular, irrelevant values as na_values

In [ ]:
pd.read_csv('aug_train.csv')

In [ ]:
pd.read_csv('aug_train.csv',na_values=['Male','-'])

## 16. Loading a huge dataset in chunks
1. Handing huge datasets by breaking into small dataframes

In [ ]:
dfs = pd.read_csv('aug_train.csv').info()

In [ ]:
dfs = pd.read_csv('aug_train.csv',chunksize=5000)

In [ ]:
for chunks in dfs:
    print(chunks.shape)