# Lab 3 - Pandas Basics (EDA Course)

**Pandas** is the library used to load, explore, clean, and summarize tabular data (rows and columns, like an Excel sheet) in Python. It is built on top of NumPy.

This notebook is written for a **first-time reader** - every new idea is explained in plain English, either in a short note right before the code, or as a comment on the exact line it applies to. Just run each cell from top to bottom.

**The two core pandas objects:**
- `Series` -> a single column of data (a 1-D labeled array)
- `DataFrame` -> a full table made of many `Series` side by side (a 2-D labeled table)

In [1]:
import pandas as pd
import numpy as np
print("Pandas version:", pd.__version__)

Pandas version: 2.2.3

---
## 1. Creating and Inspecting a DataFrame

A DataFrame can be built from a Python dictionary: each **key** becomes a column name, each **value** (a list) becomes that column's data.

In [6]:
data = {
    'Name':    ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Age':     [20, 22, 21, 23, 20],
    'Marks':   [85, 78, 92, 88, 75],
    'Subject': ['Math', 'Science', 'Math', 'Science', 'Math']
}
df = pd.DataFrame(data)
df   # in Jupyter, just writing a DataFrame's name (as the last line) displays it as a table

      Name  Age  Marks  Subject
0    Alice   20     85     Math
1      Bob   22     78  Science
2  Charlie   21     92     Math
3    Diana   23     88  Science
4      Eve   20     75     Math

In real projects your data usually already exists as a file, so you load it instead of typing it out:
```python
df.to_csv('students.csv', index=False)   # save a DataFrame to a CSV file
df = pd.read_csv('students.csv')          # load a CSV file back into a DataFrame
```
`index=False` when saving means "don't write the row numbers as an extra column" - we'll keep working with the in-memory `df` below.

In [3]:
# .shape -> a quick way to see the size of the table: (number_of_rows, number_of_columns)
print("Shape (rows, columns):", df.shape)

# .columns -> lists every column name, useful when a DataFrame has many columns
print("Column names:", list(df.columns))

# .dtypes -> shows the data type pandas assigned to each column
# (int64 = whole numbers, float64 = decimals, object = usually text/strings)
print("\nData types:")
print(df.dtypes)

Shape (rows, columns): (5, 4)
Column names: ['Name', 'Age', 'Marks', 'Subject']

Data types:
Name         str
Age        int64
Marks      int64
Subject      str
dtype: object

In [4]:
# .info() -> a one-stop summary: column names, how many NON-missing values each
# column has, the dtype, and how much memory the DataFrame uses. Great first
# command to run on any new dataset.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      str
 1   Age      5 non-null      int64
 2   Marks    5 non-null      int64
 3   Subject  5 non-null      str
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [5]:
# .describe() -> statistical summary (count, mean, std, min, quartiles, max)
# for every NUMERIC column only. Text columns are skipped by default.
df.describe()

            Age      Marks
count   5.00000   5.000000
mean   21.20000  83.600000
std     1.30384   7.021396
min    20.00000  75.000000
25%    20.00000  78.000000
50%    21.00000  85.000000
75%    22.00000  88.000000
max    23.00000  92.000000

In [6]:
# .head(n) -> first n rows, useful to "peek" at a large dataset without printing it all
print("First 3 rows:")
print(df.head(3))

# .tail(n) -> last n rows, useful to check the end of a dataset
print("\nLast 2 rows:")
print(df.tail(2))

First 3 rows:
      Name  Age  Marks  Subject
0    Alice   20     85     Math
1      Bob   22     78  Science
2  Charlie   21     92     Math

Last 2 rows:
    Name  Age  Marks  Subject
3  Diana   23     88  Science
4    Eve   20     75     Math

---
## 2. Selecting Rows and Columns

Pandas gives you a few different ways to "slice" a table. The two you'll use constantly:
- **`.loc[]`** -> select by **label** (row/column names)
- **`.iloc[]`** -> select by **integer position** (0, 1, 2, ... like a list index)

In [7]:
df2 = pd.DataFrame({
    'A': [10, 20, 30, 40, 50],
    'B': [15, 25, 35, 45, 55],
    'C': ['x', 'y', 'z', 'x', 'y']
}, index=['r1', 'r2', 'r3', 'r4', 'r5'])   # custom row labels instead of default 0,1,2...
df2

     A   B  C
r1  10  15  x
r2  20  25  y
r3  30  35  z
r4  40  45  x
r5  50  55  y

In [8]:
print("Column A only:\n", df2['A'])              # a single [ ] with a column name -> returns a Series
print("\nColumns A and B:\n", df2[['A', 'B']])   # a LIST of column names inside [ ] -> returns a DataFrame

print("\nRow 'r3' (by label):\n", df2.loc['r3'])       # .loc -> select by the row's LABEL
print("\nRow at position 2 (by position):\n", df2.iloc[2])   # .iloc -> select by position, 0-indexed (r1=0, r2=1, r3=2)

# a single value: row label 'r4', column 'B'
print("\nSingle value at r4, B:", df2.loc['r4', 'B'])

Column A only:
 r1    10
r2    20
r3    30
r4    40
r5    50
Name: A, dtype: int64

Columns A and B:
      A   B
r1  10  15
r2  20  25
r3  30  35
r4  40  45
r5  50  55

Row 'r3' (by label):
 A    30
B    35
C     z
Name: r3, dtype: object

Row at position 2 (by position):
 A    30
B    35
C     z
Name: r3, dtype: object

Single value at r4, B: 45

In [9]:
# .loc slicing with LABELS is INCLUSIVE on both ends (unlike normal Python slicing)
print("loc['r2':'r4', 'A':'B']:\n", df2.loc['r2':'r4', 'A':'B'])

# .iloc slicing with POSITIONS follows normal Python rules -> stop is EXCLUDED
print("\niloc[1:4, 0:2]:\n", df2.iloc[1:4, 0:2])

loc['r2':'r4', 'A':'B']:
      A   B
r2  20  25
r3  30  35
r4  40  45

iloc[1:4, 0:2]:
      A   B
r2  20  25
r3  30  35
r4  40  45

In [10]:
# Boolean filtering: writing a condition on a column gives True/False per row,
# and using that inside [ ] keeps only the True rows. This is the most common
# way to filter data in pandas.
print("Rows where A > 25:\n", df2[df2['A'] > 25])

# .isin([...]) -> keep rows where the column's value is ANY of the listed values
print("\nRows where C is 'x' or 'z':\n", df2[df2['C'].isin(['x', 'z'])])

# .between(low, high) -> keep rows where the value falls in that range (inclusive)
print("\nRows where B is between 20 and 45:\n", df2[df2['B'].between(20, 45)])

Rows where A > 25:
      A   B  C
r3  30  35  z
r4  40  45  x
r5  50  55  y

Rows where C is 'x' or 'z':
      A   B  C
r1  10  15  x
r3  30  35  z
r4  40  45  x

Rows where B is between 20 and 45:
      A   B  C
r2  20  25  y
r3  30  35  z
r4  40  45  x

---
## 3. Handling Missing Data

Real-world data almost always has gaps. Pandas represents a missing value as `NaN` (Not a Number, from NumPy).

In [11]:
df3 = pd.DataFrame({
    'Name':    ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'],
    'Age':     [20, np.nan, 21, 23, np.nan, 22],
    'Marks':   [85, 78, np.nan, 88, 75, np.nan],
    'Subject': ['Math', 'Science', 'Math', np.nan, 'Math', 'Science']
})
df3

      Name   Age  Marks  Subject
0    Alice  20.0   85.0     Math
1      Bob   NaN   78.0  Science
2  Charlie  21.0    NaN     Math
3    Diana  23.0   88.0      NaN
4      Eve   NaN   75.0     Math
5    Frank  22.0    NaN  Science

In [12]:
# .isnull() -> a True/False table showing WHERE values are missing
print("Boolean mask of missing values:")
print(df3.isnull())

# .isnull().sum() -> counts True values (missing values) in EACH column
print("\nMissing values per column:")
print(df3.isnull().sum())

# chaining another .sum() adds up those column totals into ONE grand total
print("\nTotal missing values in the whole DataFrame:", df3.isnull().sum().sum())

Boolean mask of missing values:
    Name    Age  Marks  Subject
0  False  False  False    False
1  False   True  False    False
2  False  False   True    False
3  False  False  False     True
4  False   True  False    False
5  False  False   True    False

Missing values per column:
Name       0
Age        2
Marks      2
Subject    1
dtype: int64

Total missing values in the whole DataFrame: 5

In [13]:
# dropna() -> removes any ROW that has at least one missing value
df_dropped = df3.dropna()
print("Rows remaining after dropna():", len(df_dropped))
print(df_dropped)

# dropna(how='all') -> removes a row ONLY if EVERY value in it is missing
# (much less aggressive - keeps rows that are just partially incomplete)
df_dropped_all = df3.dropna(how='all')
print("\nRows remaining after dropna(how='all'):", len(df_dropped_all))

Rows remaining after dropna(): 1
    Name   Age  Marks Subject
0  Alice  20.0   85.0    Math

Rows remaining after dropna(how='all'): 6

In [14]:
df3_filled = df3.copy()   # .copy() so we don't overwrite the original df3

# fillna(value) -> replaces missing values with the given value.
# Numeric columns are commonly filled with the mean or median.
df3_filled['Age'] = df3_filled['Age'].fillna(df3_filled['Age'].mean())      # mean = average
df3_filled['Marks'] = df3_filled['Marks'].fillna(df3_filled['Marks'].median())  # median = middle value (less affected by outliers)

# For a text/category column, the most common value (the "mode") is a
# reasonable fill choice. .mode() can return multiple values if there's a
# tie, so we take the first one with [0].
df3_filled['Subject'] = df3_filled['Subject'].fillna(df3_filled['Subject'].mode()[0])

df3_filled

      Name   Age  Marks  Subject
0    Alice  20.0   85.0     Math
1      Bob  21.5   78.0  Science
2  Charlie  21.0   81.5     Math
3    Diana  23.0   88.0     Math
4      Eve  21.5   75.0     Math
5    Frank  22.0   81.5  Science

**`dropna()` vs `fillna()` - when to use which?**
Use `dropna()` when only a small number of rows have missing data and losing them won't bias your analysis - it's simple and safe. Use `fillna()` when missing rows are too many to discard, or when the column is important enough that you'd rather keep an estimated value (mean/median/mode) than lose the whole row. As a rule of thumb: drop when missing data is rare and random, fill when it's common or you need to preserve every row.

---
## 4. Cleaning: Duplicates, Data Types, Renaming

In [15]:
df4 = pd.DataFrame({
    'Student_ID': ['S001', 'S002', 'S003', 'S001', 'S004', 'S002'],
    'Join_Date':  ['2023-01-15', '2023-02-20', '2023-03-10', '2023-01-15', '2023-04-05', '2023-02-20'],
    'Score':      ['85.5', '78.0', '92.3', '85.5', '88.1', '78.0'],   # notice: stored as TEXT, not numbers
    'Passed':     ['Yes', 'No', 'Yes', 'Yes', 'Yes', 'No']
})
df4

  Student_ID   Join_Date Score Passed
0       S001  2023-01-15  85.5    Yes
1       S002  2023-02-20  78.0     No
2       S003  2023-03-10  92.3    Yes
3       S001  2023-01-15  85.5    Yes
4       S004  2023-04-05  88.1    Yes
5       S002  2023-02-20  78.0     No

In [16]:
# .duplicated() -> True for a row that is an EXACT repeat of an earlier row
print("Duplicate flags:\n", df4.duplicated())
print("\nTotal duplicate rows:", df4.duplicated().sum())

# drop_duplicates() -> keeps only the FIRST occurrence of each duplicated row
df4_clean = df4.drop_duplicates()
print("\nAfter removing duplicates:")
print(df4_clean)

Duplicate flags:
 0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

Total duplicate rows: 2

After removing duplicates:
  Student_ID   Join_Date Score Passed
0       S001  2023-01-15  85.5    Yes
1       S002  2023-02-20  78.0     No
2       S003  2023-03-10  92.3    Yes
4       S004  2023-04-05  88.1    Yes

In [17]:
df4_clean = df4_clean.copy()

# astype(float) -> converts the Score column from text ("85.5") to a real number (85.5)
# This matters because you CANNOT do math (mean, sum, comparisons) on text.
df4_clean['Score'] = df4_clean['Score'].astype(float)

# pd.to_datetime() -> converts text dates into pandas' proper datetime type,
# which unlocks date-specific operations (sorting by date, extracting the
# month/year, computing the number of days between two dates, etc).
df4_clean['Join_Date'] = pd.to_datetime(df4_clean['Join_Date'])

# Converting "Yes"/"No" text into True/False boolean values
df4_clean['Passed'] = df4_clean['Passed'].map({'Yes': True, 'No': False})

print(df4_clean.dtypes)
df4_clean

Student_ID               str
Join_Date     datetime64[us]
Score                float64
Passed                  bool
dtype: object

  Student_ID  Join_Date  Score  Passed
0       S001 2023-01-15   85.5    True
1       S002 2023-02-20   78.0   False
2       S003 2023-03-10   92.3    True
4       S004 2023-04-05   88.1    True

In [18]:
# rename(columns={old_name: new_name}) -> renames one or more columns.
# inplace=True means "apply the change directly to df4_clean" instead of
# returning a new copy that you'd have to reassign.
df4_clean.rename(columns={'Student_ID': 'ID', 'Join_Date': 'Enrollment_Date'}, inplace=True)
df4_clean

     ID Enrollment_Date  Score  Passed
0  S001      2023-01-15   85.5    True
1  S002      2023-02-20   78.0   False
2  S003      2023-03-10   92.3    True
4  S004      2023-04-05   88.1    True

In [19]:
# replace(old, new) -> swaps specific values for new ones anywhere in a column.
# Here we turn the boolean-ish Yes/No style into 1/0, which is often more
# convenient for later numeric analysis (e.g. computing a "pass rate" as a mean).
df4_clean['Passed'] = df4_clean['Passed'].replace({True: 1, False: 0})
df4_clean

     ID Enrollment_Date  Score Passed
0  S001      2023-01-15   85.5      1
1  S002      2023-02-20   78.0      0
2  S003      2023-03-10   92.3      1
4  S004      2023-04-05   88.1      1

**Why convert data types before analysis?**
Pandas can only compute statistics (mean, sum, correlation, comparisons like `>`) on columns that hold actual numbers or dates - a column stored as text looks like data but behaves like a string, so `"85.5" + "78.0"` would concatenate text instead of adding numbers. Converting types up front prevents these silent errors and makes sure every later calculation is mathematically correct.

---
## 5. Sorting and Ranking

In [20]:
df5 = pd.DataFrame({
    'Name':       ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'],
    'Marks':      [85, 78, 92, 88, 75, 91],
    'Attendance': [90, 85, 95, 80, 88, 92]
})

# sort_values(column) -> reorders ROWS by a column's value; ascending=True is the default
print("Sorted by Marks (ascending):\n", df5.sort_values('Marks'))
print("\nSorted by Marks (descending):\n", df5.sort_values('Marks', ascending=False))

Sorted by Marks (ascending):
       Name  Marks  Attendance
4      Eve     75          88
1      Bob     78          85
0    Alice     85          90
3    Diana     88          80
5    Frank     91          92
2  Charlie     92          95

Sorted by Marks (descending):
       Name  Marks  Attendance
2  Charlie     92          95
5    Frank     91          92
3    Diana     88          80
0    Alice     85          90
1      Bob     78          85
4      Eve     75          88

In [21]:
# Sorting by MULTIPLE columns: ties in the first column are broken using the second.
# The 'by' and 'ascending' lists line up position-by-position.
df5_multi = df5.sort_values(by=['Attendance', 'Marks'], ascending=[True, False])
print(df5_multi)

      Name  Marks  Attendance
3    Diana     88          80
1      Bob     78          85
4      Eve     75          88
0    Alice     85          90
5    Frank     91          92
2  Charlie     92          95

In [22]:
df5 = df5.copy()

# rank() -> assigns a rank number to each value. ascending=False means the
# HIGHEST mark gets rank 1. method='min' -> if there's a tie, both rows get
# the same (lower) rank number, e.g. two people tied for 2nd both get rank 2.
df5['Rank'] = df5['Marks'].rank(method='min', ascending=False)

# method='dense' -> similar to 'min', but the NEXT rank after a tie doesn't
# skip a number (e.g. ranks go 1,2,2,3 instead of 1,2,2,4).
df5['Attendance_Rank'] = df5['Attendance'].rank(method='dense', ascending=False)

df5

      Name  Marks  Attendance  Rank  Attendance_Rank
0    Alice     85          90   4.0              3.0
1      Bob     78          85   5.0              5.0
2  Charlie     92          95   1.0              1.0
3    Diana     88          80   3.0              6.0
4      Eve     75          88   6.0              4.0
5    Frank     91          92   2.0              2.0

In [23]:
# nlargest(n, column) / nsmallest(n, column) -> quick shortcuts to get the
# top or bottom N rows by a column, without sorting the whole DataFrame yourself.
print("Top 3 by Marks:\n", df5.nlargest(3, 'Marks'))
print("\nBottom 2 by Attendance:\n", df5.nsmallest(2, 'Attendance'))

Top 3 by Marks:
       Name  Marks  Attendance  Rank  Attendance_Rank
2  Charlie     92          95   1.0              1.0
5    Frank     91          92   2.0              2.0
3    Diana     88          80   3.0              6.0

Bottom 2 by Attendance:
     Name  Marks  Attendance  Rank  Attendance_Rank
3  Diana     88          80   3.0              6.0
1    Bob     78          85   5.0              5.0

In [24]:
# After sorting, the row index (labels) gets shuffled out of order.
# reset_index(drop=True) -> replaces it with a clean 0,1,2,... index.
# drop=True means "throw away the old index" instead of keeping it as a new column.
df5_sorted = df5.sort_values('Marks', ascending=False).reset_index(drop=True)
df5_sorted

      Name  Marks  Attendance  Rank  Attendance_Rank
0  Charlie     92          95   1.0              1.0
1    Frank     91          92   2.0              2.0
2    Diana     88          80   3.0              6.0
3    Alice     85          90   4.0              3.0
4      Bob     78          85   5.0              5.0
5      Eve     75          88   6.0              4.0

---
## 6. GroupBy - Summarizing Data by Category

`groupby()` follows a "split - apply - combine" pattern: **split** the data into groups (e.g. by Department), **apply** a calculation to each group separately, then **combine** the results into one table.

In [25]:
df6 = pd.DataFrame({
    'Department': ['Sales', 'IT', 'Sales', 'HR', 'IT', 'HR', 'Sales', 'IT'],
    'Employee':   ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace', 'Henry'],
    'Salary':     [50000, 70000, 55000, 45000, 75000, 48000, 60000, 72000],
    'Experience': [2, 5, 3, 4, 6, 3, 4, 7]
})

print("Average Salary per Department:\n", df6.groupby('Department')['Salary'].mean())
print("\nTotal Salary per Department:\n", df6.groupby('Department')['Salary'].sum())

# .size() -> how many rows fall into each group (i.e. how many employees per department)
print("\nEmployees per Department:\n", df6.groupby('Department').size())

Average Salary per Department:
 Department
HR       46500.000000
IT       72333.333333
Sales    55000.000000
Name: Salary, dtype: float64

Total Salary per Department:
 Department
HR        93000
IT       217000
Sales    165000
Name: Salary, dtype: int64

Employees per Department:
 Department
HR       2
IT       3
Sales    3
dtype: int64

In [26]:
# .agg([...]) -> apply SEVERAL functions at once to a column, all in one call
print("Min / Max / Mean Experience per Department:")
print(df6.groupby('Department')['Experience'].agg(['min', 'max', 'mean']))

# .agg({col: func, ...}) -> apply a DIFFERENT function to each column at once
print("\nMean Salary and total Experience per Department:")
print(df6.groupby('Department').agg({'Salary': 'mean', 'Experience': 'sum'}))

Min / Max / Mean Experience per Department:
            min  max  mean
Department
HR            3    4   3.5
IT            5    7   6.0
Sales         2    4   3.0

Mean Salary and total Experience per Department:
                  Salary  Experience
Department
HR          46500.000000           7
IT          72333.333333          18
Sales       55000.000000           9

In [27]:
# transform() vs agg(): agg() COLLAPSES each group into one summary row.
# transform() keeps the ORIGINAL number of rows, but replaces each value with
# a group-level result - so it can be attached back as a new column, aligned
# with every individual employee.
df6['Dept_Avg_Salary'] = df6.groupby('Department')['Salary'].transform('mean')
df6

  Department Employee  Salary  Experience  Dept_Avg_Salary
0      Sales    Alice   50000           2     55000.000000
1         IT      Bob   70000           5     72333.333333
2      Sales  Charlie   55000           3     55000.000000
3         HR    Diana   45000           4     46500.000000
4         IT      Eve   75000           6     72333.333333
5         HR    Frank   48000           3     46500.000000
6      Sales    Grace   60000           4     55000.000000
7         IT    Henry   72000           7     72333.333333

In [28]:
# To filter GROUPS (not individual rows), first compute a group summary,
# then use it to decide which department names to keep.
dept_avg = df6.groupby('Department')['Salary'].mean()
high_paying_depts = dept_avg[dept_avg > 55000].index   # department names where avg salary > 55000
print("High paying departments:", list(high_paying_depts))
print(df6[df6['Department'].isin(high_paying_depts)])

High paying departments: ['IT']
  Department Employee  Salary  Experience  Dept_Avg_Salary
1         IT      Bob   70000           5     72333.333333
4         IT      Eve   75000           6     72333.333333
7         IT    Henry   72000           7     72333.333333

**`agg()` vs `transform()`?**
`agg()` reduces each group down to a single summary value per group (e.g. one average salary per department), so the result has fewer rows than the original data. `transform()` returns a result with the SAME number of rows as the original DataFrame, repeating the group's summary value for every row in that group - which makes it perfect for adding a new "group average" column back onto the original data for comparison.

---
## 7. Statistical Analysis and Value Counts

In [29]:
df7 = pd.DataFrame({
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A'],
    'Sales':   [120, 200, 150, 180, 220, 130, 190, 210, 160, 175],
    'Rating':  [4.2, 3.8, 4.5, 4.0, 3.9, 4.3, 4.1, 4.0, 4.4, 3.7],
    'Region':  ['East', 'West', 'East', 'North', 'West', 'South', 'East', 'West', 'South', 'North']
})

print(f"Sales  -> mean: {df7['Sales'].mean():.2f}, median: {df7['Sales'].median()}, std: {df7['Sales'].std():.2f}")
print(f"Rating -> mean: {df7['Rating'].mean():.2f}, median: {df7['Rating'].median()}, std: {df7['Rating'].std():.2f}")
print(f"\nSales min: {df7['Sales'].min()}, max: {df7['Sales'].max()}, range: {df7['Sales'].max() - df7['Sales'].min()}")

# quantile(0.25/0.5/0.75) -> the value below which that fraction of the data falls
print(f"\nSales quartiles -> 25%: {df7['Sales'].quantile(0.25)}, 50%: {df7['Sales'].quantile(0.50)}, 75%: {df7['Sales'].quantile(0.75)}")

Sales  -> mean: 173.50, median: 177.5, std: 33.34
Rating -> mean: 4.09, median: 4.05, std: 0.26

Sales min: 120, max: 220, range: 100

Sales quartiles -> 25%: 152.5, 50%: 177.5, 75%: 197.5

In [30]:
# .corr() -> a correlation matrix: how strongly each numeric column moves
# together with each other, from -1 (perfectly opposite) to +1 (perfectly together).
# Only works between numeric columns (Region and Product are text, so they're skipped).
print("Correlation matrix:")
print(df7.corr(numeric_only=True))

# .cov() -> covariance matrix, similar idea but NOT scaled to a fixed -1..1
# range, so it's harder to compare across different columns directly.
print("\nCovariance matrix:")
print(df7.cov(numeric_only=True))

Correlation matrix:
           Sales    Rating
Sales   1.000000 -0.636145
Rating -0.636145  1.000000

Covariance matrix:
              Sales    Rating
Sales   1111.388889 -5.516667
Rating    -5.516667  0.067667

In [31]:
# value_counts() -> counts how many times each unique value appears in a column
print("Product counts:\n", df7['Product'].value_counts())

# normalize=True -> show PROPORTIONS (fractions of the whole) instead of raw counts
print("\nRegion distribution (%):\n", df7['Region'].value_counts(normalize=True))

# nunique() -> how many DISTINCT values each column has
print("\nUnique value counts per column:\n", df7.nunique())

Product counts:
 Product
A    4
B    3
C    3
Name: count, dtype: int64

Region distribution (%):
 Region
East     0.3
West     0.3
North    0.2
South    0.2
Name: proportion, dtype: float64

Unique value counts per column:
 Product     3
Sales      10
Rating      9
Region      4
dtype: int64

---
## 8. Transforming Data: apply(), map(), replace()

In [32]:
df8 = pd.DataFrame({
    'Name':         ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Marks':        [85, 78, 92, 88, 75],
    'Grade_Letter': ['B', 'C', 'A', 'A', 'C']
})

# .apply(function) on a Series -> runs the function on EVERY value in that column
df8['Marks_Squared'] = df8['Marks'].apply(lambda x: x ** 2)

# lambda -> a small, unnamed, "throwaway" function written in one line, handy
# for simple logic you don't want to define with a full "def" elsewhere.
df8['Category'] = df8['Marks'].apply(lambda x: 'High' if x >= 85 else ('Medium' if x >= 70 else 'Low'))

# .map(dictionary) -> looks up each value in the dictionary and replaces it
# with the matching result. Best for simple 1-to-1 value substitutions.
grade_points = {'A': 4, 'B': 3, 'C': 2, 'D': 1, 'F': 0}
df8['Grade_Points'] = df8['Grade_Letter'].map(grade_points)

df8

      Name  Marks Grade_Letter  Marks_Squared Category  Grade_Points
0    Alice     85            B           7225     High             3
1      Bob     78            C           6084   Medium             2
2  Charlie     92            A           8464     High             4
3    Diana     88            A           7744     High             4
4      Eve     75            C           5625   Medium             2

In [33]:
# replace(old, new) -> substitute specific values anywhere in a column
df8['Name'] = df8['Name'].replace('Charlie', 'Chris')

# .apply() can also run on an ENTIRE DataFrame at once (column by column) -
# here we uppercase every text value across the whole table.
df8_upper = df8.apply(lambda col: col.map(lambda v: v.upper() if isinstance(v, str) else v))
df8_upper

    Name  Marks Grade_Letter  Marks_Squared Category  Grade_Points
0  ALICE     85            B           7225     HIGH             3
1    BOB     78            C           6084   MEDIUM             2
2  CHRIS     92            A           8464     HIGH             4
3  DIANA     88            A           7744     HIGH             4
4    EVE     75            C           5625   MEDIUM             2

**`apply()` vs `map()` vs `applymap()`?**
`map()` works on a single Series (column) and is meant for simple element-wise lookups or substitutions (e.g. a dictionary). `apply()` is more general - it works on a Series OR a whole DataFrame, and can run any custom function, including ones using multiple columns at once. `applymap()` (older pandas) ran a function on every individual cell of a whole DataFrame; in modern pandas this is done with `df.apply(func)` combined with `.map()` per column, as shown above. Use `map()` for simple substitutions, `apply()` for anything needing custom logic.

---
## 9. Merging, Joining, and Concatenating

`merge()` combines two DataFrames based on a **shared key column** (like a SQL join). `concat()` simply **stacks** DataFrames together, either on top of each other or side by side.

In [34]:
df1 = pd.DataFrame({'ID': [1, 2, 3, 4], 'Name': ['Alice', 'Bob', 'Charlie', 'Diana']})
df2 = pd.DataFrame({'ID': [3, 4, 5, 6], 'Salary': [50000, 60000, 70000, 80000]})
df3 = pd.DataFrame({'ID': [7, 8], 'Name': ['Eve', 'Frank'], 'Salary': [55000, 65000]})

print("df1:\n", df1)
print("\ndf2:\n", df2)

df1:
    ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    Diana

df2:
    ID  Salary
0   3   50000
1   4   60000
2   5   70000
3   6   80000

In [35]:
# inner join -> keeps ONLY the IDs that exist in BOTH DataFrames (the overlap)
inner = df1.merge(df2, on='ID', how='inner')
print("Inner join (IDs 3 and 4 only, the overlap):\n", inner)

# left join -> keeps ALL rows from the LEFT DataFrame (df1), and fills in
# missing info from df2 with NaN where there's no match
left = df1.merge(df2, on='ID', how='left')
print("\nLeft join (all of df1, Salary is NaN for IDs 1 and 2):\n", left)

# right join -> mirror of left join: keeps ALL rows from the RIGHT DataFrame (df2)
right = df1.merge(df2, on='ID', how='right')
print("\nRight join (all of df2, Name is NaN for IDs 5 and 6):\n", right)

# outer join -> keeps EVERY ID from BOTH DataFrames, filling NaN wherever data is missing
outer = df1.merge(df2, on='ID', how='outer')
print("\nOuter join (every ID from both, most rows, most NaNs):\n", outer)

Inner join (IDs 3 and 4 only, the overlap):
    ID     Name  Salary
0   3  Charlie   50000
1   4    Diana   60000

Left join (all of df1, Salary is NaN for IDs 1 and 2):
    ID     Name   Salary
0   1    Alice      NaN
1   2      Bob      NaN
2   3  Charlie  50000.0
3   4    Diana  60000.0

Right join (all of df2, Name is NaN for IDs 5 and 6):
    ID     Name  Salary
0   3  Charlie   50000
1   4    Diana   60000
2   5      NaN   70000
3   6      NaN   80000

Outer join (every ID from both, most rows, most NaNs):
    ID     Name   Salary
0   1    Alice      NaN
1   2      Bob      NaN
2   3  Charlie  50000.0
3   4    Diana  60000.0
4   5      NaN  70000.0
5   6      NaN  80000.0

In [36]:
# concat(axis=0) -> stacks DataFrames VERTICALLY (adds more ROWS) - useful
# when you have new records in the same shape/columns as existing data.
stacked_rows = pd.concat([df1, df3], axis=0)
print("Concat axis=0 (row-wise):\n", stacked_rows)

# concat(axis=1) -> places DataFrames SIDE BY SIDE (adds more COLUMNS),
# matching rows purely by their POSITION/index - not by any shared key like merge() does.
# Since df1 and df2 don't have the same number of rows / matching indexes here,
# you'll see NaNs wherever the row positions don't correspond to the same entity.
stacked_cols = pd.concat([df1, df2], axis=1)
print("\nConcat axis=1 (column-wise):\n", stacked_cols)

Concat axis=0 (row-wise):
    ID     Name   Salary
0   1    Alice      NaN
1   2      Bob      NaN
2   3  Charlie      NaN
3   4    Diana      NaN
0   7      Eve  55000.0
1   8    Frank  65000.0

Concat axis=1 (column-wise):
    ID     Name  ID  Salary
0   1    Alice   3   50000
1   2      Bob   4   60000
2   3  Charlie   5   70000
3   4    Diana   6   80000

**`merge()` vs `concat()`?**
`merge()` combines two tables intelligently using a shared key column, matching rows by their actual relationship (like a SQL join) - use it when you're combining related but separately-stored information (e.g. employee names and their salaries). `concat()` simply stacks DataFrames together without matching on any key - use it when you're adding more rows of the same kind of data, or placing already-aligned tables side by side.

**Inner join vs outer join during EDA?**
Use an inner join when you only want records that are complete and present in every dataset you're combining - it's the safest choice for clean analysis, since it guarantees no missing values from the join itself. Use an outer join when you don't want to lose any records, even if some information is missing (NaN) for them - useful during early EDA when you want to see the full picture, including gaps, before deciding how to handle them.

---
## 10. Pivot Tables and Cross-Tabulation

In [37]:
df10 = pd.DataFrame({
    'Region':  ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Product': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B', 'B', 'A'],
    'Sales':   [200, 150, 300, 250, 180, 220, 280, 260, 190, 210],
    'Profit':  [50, 30, 80, 60, 45, 55, 70, 65, 40, 52]
})

# pivot_table(values, index, columns, aggfunc) -> reshapes the data into a
# grid: one column's values become the ROWS, another's become the COLUMNS,
# and the cells hold an aggregated (e.g. averaged) number.
avg_sales_pivot = df10.pivot_table(values='Sales', index='Region', columns='Product', aggfunc='mean')
print("Average Sales by Region and Product:\n", avg_sales_pivot)

total_profit_pivot = df10.pivot_table(values='Profit', index='Region', columns='Product', aggfunc='sum')
print("\nTotal Profit by Region and Product:\n", total_profit_pivot)

Average Sales by Region and Product:
 Product      A      B
Region
East     280.0  300.0
North    190.0  190.0
South    180.0  220.0
West       NaN  255.0

Total Profit by Region and Product:
 Product     A      B
Region
East     70.0   80.0
North    95.0   40.0
South    82.0   55.0
West      NaN  125.0

In [38]:
# You can also compute multiple aggregations for multiple columns in one pivot table
multi_pivot = df10.pivot_table(values=['Sales', 'Profit'], index='Region', aggfunc={'Sales': 'mean', 'Profit': 'sum'})
print(multi_pivot)

        Profit       Sales
Region
East       150  290.000000
North      135  190.000000
South      137  193.333333
West       125  255.000000

In [39]:
# pd.crosstab(row_variable, column_variable) -> a frequency table: simply
# COUNTS how many times each Region/Product combination appears.
freq_table = pd.crosstab(df10['Region'], df10['Product'])
print("Frequency of each Region-Product combination:\n", freq_table)

# normalize=True -> shows the PROPORTION of the grand total instead of raw counts
prop_table = pd.crosstab(df10['Region'], df10['Product'], normalize=True)
print("\nAs proportions of the total:\n", prop_table)

# margins=True -> adds an extra "All" row and column with the row/column totals
margin_table = pd.crosstab(df10['Region'], df10['Product'], margins=True)
print("\nWith row/column totals:\n", margin_table)

Frequency of each Region-Product combination:
 Product  A  B
Region
East     1  1
North    2  1
South    2  1
West     0  2

As proportions of the total:
 Product    A    B
Region
East     0.1  0.1
North    0.2  0.1
South    0.2  0.1
West     0.0  0.2

With row/column totals:
 Product  A  B  All
Region
East     1  1    2
North    2  1    3
South    2  1    3
West     0  2    2
All      5  5   10

**When is `pivot_table()` more useful than `groupby()`?**
`pivot_table()` shines when you want to summarize data across **two categorical dimensions at once**, laid out as a readable grid (rows x columns) - like Region vs Product - which would take several extra steps to arrange manually from a plain `groupby()`. Use `groupby()` for simpler, single-dimension summaries or when you need to chain further custom operations.

**Pivot table vs cross-tabulation (`crosstab`)?**
A pivot table summarizes a NUMERIC column (like average Sales) across two categories. A crosstab specifically counts FREQUENCIES - how many rows fall into each combination of two categorical columns - without needing a numeric column to aggregate at all.

---
## Summary

- Always start with `.shape`, `.info()`, `.describe()`, `.head()` to get a feel for new data.
- `.loc[]` selects by label, `.iloc[]` selects by position - both support slicing and boolean filtering.
- Handle missing data with `dropna()` (remove) or `fillna()` (estimate and keep).
- Clean data by removing `duplicated()` rows and fixing `dtypes` with `astype()` / `pd.to_datetime()` before doing any math.
- `groupby()` + `agg()` summarizes by category; `transform()` keeps the original row count so you can compare each row to its group.
- `merge()` joins on a shared key (inner/left/right/outer); `concat()` just stacks DataFrames together.
- `pivot_table()` and `crosstab()` reshape data into an easy-to-read grid across two categories.