## Q1. Creating and Inspecting DataFrames

Create a CSV file named students.csv with the following data. Then load it using pandas and
inspect the DataFrame.

import pandas as pd

data = {

'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],

'Age': [20, 22, 21, 23, 20],

'Marks': [85, 78, 92, 88, 75],

'Subject': ['Math', 'Science', 'Math', 'Science', 'Math']

}

df = pd.DataFrame(data)

df.to_csv('students.csv', index=False)

df = pd.read_csv('students.csv')


Perform the following tasks:

• Display the entire DataFrame to see all rows and columns.

• Use shape to find the total number of rows and columns.

• Use columns to print all column names.

• Use dtypes to check the data type of each column.

• Use info() to see column names, non-null counts, and memory
usage.

• Use describe() to get statistical summary for numeric columns.

• Use head(3) to display only the first 3 rows.

• Use tail(2) to display only the last 2 rows

In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Age': [20, 22, 21, 23, 20],
    'Marks': [85, 78, 92, 88, 75],
    'Subject': ['Math', 'Science', 'Math', 'Science', 'Math']
}

df = pd.DataFrame(data)
df.to_csv('students.csv', index=False)

df = pd.read_csv('students.csv')
df

      Name  Age  Marks  Subject
0    Alice   20     85     Math
1      Bob   22     78  Science
2  Charlie   21     92     Math
3    Diana   23     88  Science
4      Eve   20     75     Math

In [3]:
df.shape

(5, 4)

shape tells number of rows and number of columns

In [ ]:
df.columns

Index(['Name', 'Age', 'Marks', 'Subject'], dtype='object')

df.columns prints the names of all columns.

In [ ]:
df.dtypes

Name       object
Age         int64
Marks       int64
Subject    object
dtype: object

df.dtypes shows whether each column holds int,float,object.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   Age      5 non-null      int64
 2   Marks    5 non-null      int64
 3   Subject  5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

df.info() gives a summary column names, how many non-empty values each has, and memory used.

In [5]:
df.describe()

            Age      Marks
count   5.00000   5.000000
mean   21.20000  83.600000
std     1.30384   7.021396
min    20.00000  75.000000
25%    20.00000  78.000000
50%    21.00000  85.000000
75%    22.00000  88.000000
max    23.00000  92.000000

df.describe() gives statistics (count, mean, min, max, etc.) but only for number columns (Age, Marks)

In [ ]:
df.head(3) # these get first 3 row of the dataframe

      Name  Age  Marks  Subject
0    Alice   20     85     Math
1      Bob   22     78  Science
2  Charlie   21     92     Math

In [ ]:
df.tail(2) # these get last 2 row of dataframe

    Name  Age  Marks  Subject
3  Diana   23     88  Science
4    Eve   20     75     Math

## Q2. Data Selection and Indexing

Create a CSV file named matrix_data.csv with the following data. Then load it and practice
selecting specific rows, columns, and values using different pandas methods.

import pandas as pd

df = pd.DataFrame({

'A': [10, 20, 30, 40, 50],

'B': [15, 25, 35, 45, 55],

'C': ['x', 'y', 'z', 'x', 'y']

}, index=['r1', 'r2', 'r3', 'r4', 'r5'])

df.to_csv('matrix_data.csv')

df = pd.read_csv('matrix_data.csv', index_col=0)

Perform the following tasks:

• Select column A using bracket notation: df['A'].

• Select columns A and B together: df[['A', 'B']].

• Select row with label 'r3' using loc['r3'].

• Select row at position 2 using iloc[2].

• Select the single value at row 'r4', column 'B' using loc['r4', 'B'].

• Select rows 'r2' to 'r4' and columns 'A' to 'B' using loc['r2':'r4', 'A':'B'].

• Select rows at positions 1 to 3 and columns at positions 0 to 1 using iloc[1:4, 0:2].

• Select all rows where column A values are greater than 25 using boolean filtering.

• Select rows where column C is either 'x' or 'z' using isin(['x', 'z']).

• Select rows where column B is between 20 and 45 (inclusive) using between(20, 45).

In [7]:
df = pd.DataFrame({
    'A': [10, 20, 30, 40, 50],
    'B': [15, 25, 35, 45, 55],
    'C': ['x', 'y', 'z', 'x', 'y']
}, index=['r1', 'r2', 'r3', 'r4', 'r5'])

df.to_csv('matrix_data.csv')

df = pd.read_csv('matrix_data.csv', index_col=0)
df

     A   B  C
r1  10  15  x
r2  20  25  y
r3  30  35  z
r4  40  45  x
r5  50  55  y

In [ ]:
df['A']

r1    10
r2    20
r3    30
r4    40
r5    50
Name: A, dtype: int64

df['A'] selects only column A using bracket notation.

In [ ]:
df[['A', 'B']]

     A   B
r1  10  15
r2  20  25
r3  30  35
r4  40  45
r5  50  55

This selects column A and column B together as a new DataFrame.

In [ ]:
df.loc['r3']

A    30
B    35
C     z
Name: r3, dtype: object

loc['r3'] selects the row that has label r3.

In [ ]:
df.iloc[2]

A    30
B    35
C     z
Name: r3, dtype: object

iloc[2] selects the row at position 2 (position starts from 0, so this is the 3rd row, which is r3).

In [ ]:
df.loc['r4', 'B']

np.int64(45)

This gives the single value at row r4 and column B.

In [ ]:
df.loc['r2':'r4', 'A':'B']

     A   B
r2  20  25
r3  30  35
r4  40  45

This selects rows r2 to r4 and columns A to B together. With loc, both start and end labels are included.

In [ ]:
df.iloc[1:4, 0:2]

     A   B
r2  20  25
r3  30  35
r4  40  45

This selects rows at position 1 to 3 and columns at position 0 to 1. With iloc, the end position is not included.

In [ ]:
df[df['A'] > 25]

     A   B  C
r3  30  35  z
r4  40  45  x
r5  50  55  y

This uses boolean filtering to keep only the rows where column A is greater than 25.

In [ ]:
df[df['C'].isin(['x', 'z'])]

     A   B  C
r1  10  15  x
r3  30  35  z
r4  40  45  x

isin(['x','z']) keeps only rows where column C is either x or z.

In [ ]:
df[df['B'].between(20, 45)]

     A   B  C
r2  20  25  y
r3  30  35  z
r4  40  45  x

between(20,45) keeps rows where column B value is between 20 and 45, including both 20 and 45.

## Q3. Handling Missing Data
Create a CSV file named missing_data.csv with missing values. Then load it and practice
detecting, counting, and handling missing data.

import pandas as pd

import numpy as np

df = pd.DataFrame({

'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'],


'Age': [20, np.nan, 21, 23, np.nan, 22],

'Marks': [85, 78, np.nan, 88, 75, np.nan],

'Subject': ['Math', 'Science', 'Math', np.nan, 'Math', 'Science']

})

df.to_csv('missing_data.csv', index=False)

df = pd.read_csv('missing_data.csv')

Perform the following tasks:

• Use isnull() to create a boolean mask showing True where values are missing.

• Use isnull().sum() to count missing values in each column.

• Use isnull().sum().sum() to get the total number of missing values in the
entire
DataFrame.

• Use dropna() to remove all rows containing any missing value. Store in a new
variable and count how many rows remain.

• Use dropna(how='all') to remove only rows where all values are missing.

• Fill missing Age values with the mean of the Age column using fillna().

• Fill missing Marks values with the median of the Marks column.

• Fill missing Subject values with the mode (most frequent value) of the Subject
column.

• Explain in 2-3 sentences: When should you use dropna() versus fillna() during EDA?

In [ ]:
import numpy as np

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'],
    'Age': [20, np.nan, 21, 23, np.nan, 22],
    'Marks': [85, 78, np.nan, 88, 75, np.nan],
    'Subject': ['Math', 'Science', 'Math', np.nan, 'Math', 'Science']
})

df.to_csv('missing_data.csv', index=False)

df = pd.read_csv('missing_data.csv')
df

      Name   Age  Marks  Subject
0    Alice  20.0   85.0     Math
1      Bob   NaN   78.0  Science
2  Charlie  21.0    NaN     Math
3    Diana  23.0   88.0      NaN
4      Eve   NaN   75.0     Math
5    Frank  22.0    NaN  Science

In [ ]:
df.isnull()

    Name    Age  Marks  Subject
0  False  False  False    False
1  False   True  False    False
2  False  False   True    False
3  False  False  False     True
4  False   True  False    False
5  False  False   True    False

isnull() gives a table of True and False. True means the value is missing.

In [ ]:
df.isnull().sum()

Name       0
Age        2
Marks      2
Subject    1
dtype: int64

This counts how many missing values are in each column.

In [ ]:
df.isnull().sum().sum()

np.int64(5)

This adds up all the missing values from every column to give one total number.

In [ ]:
df_dropped = df.dropna()
df_dropped

    Name   Age  Marks Subject
0  Alice  20.0   85.0    Math

dropna() removes any row that has even one missing value. After dropping, [X] rows remain (check your output and fill in the number).

In [ ]:
df.dropna(how='all')

      Name   Age  Marks  Subject
0    Alice  20.0   85.0     Math
1      Bob   NaN   78.0  Science
2  Charlie  21.0    NaN     Math
3    Diana  23.0   88.0      NaN
4      Eve   NaN   75.0     Math
5    Frank  22.0    NaN  Science

dropna(how='all') only removes a row if all the values in that row are missing. Since no row here is completely empty, no rows are removed.

In [ ]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

      Name   Age  Marks  Subject
0    Alice  20.0   85.0     Math
1      Bob  21.5   78.0  Science
2  Charlie  21.0    NaN     Math
3    Diana  23.0   88.0      NaN
4      Eve  21.5   75.0     Math
5    Frank  22.0    NaN  Science

This fills the missing Age values with the mean (average) of the Age column.

In [ ]:
df['Marks'] = df['Marks'].fillna(df['Marks'].median())
df

      Name   Age  Marks  Subject
0    Alice  20.0   85.0     Math
1      Bob  21.5   78.0  Science
2  Charlie  21.0   81.5     Math
3    Diana  23.0   88.0      NaN
4      Eve  21.5   75.0     Math
5    Frank  22.0   81.5  Science

This fills the missing Marks values with the median of the Marks column.

In [ ]:
df['Subject'] = df['Subject'].fillna(df['Subject'].mode()[0])
df

      Name   Age  Marks  Subject
0    Alice  20.0   85.0     Math
1      Bob  21.5   78.0  Science
2  Charlie  21.0   81.5     Math
3    Diana  23.0   88.0     Math
4      Eve  21.5   75.0     Math
5    Frank  22.0   81.5  Science

This fills the missing Subject values with the mode, which is the value that appears most often in that column.

We use dropna() when only a few rows have missing values and removing them will not affect the analysis much. We use fillna() when many rows have missing values and we don't want to lose data, so we fill the gaps with mean, median, or mode instead of deleting rows.

## Q4. Data Cleaning: Duplicates, Types, and Renaming
Create a CSV file named cleaning_data.csv with duplicate rows and incorrect data types.
Then clean it by removing duplicates, converting types, and renaming columns.

import pandas as pd

df = pd.DataFrame({

'Student_ID': ['S001', 'S002', 'S003', 'S001', 'S004', 'S002'],

'Join_Date': ['2023-01-15', '2023-02-20', '2023-03-10',

'2023-01-15', '2023-04-05', '2023-02-20'],

'Score': ['85.5', '78.0', '92.3', '85.5', '88.1', '78.0'],

'Passed': ['Yes', 'No', 'Yes', 'Yes', 'Yes', 'No']

})

df.to_csv('cleaning_data.csv', index=False)

df = pd.read_csv('cleaning_data.csv')

Perform the following tasks:

• Use duplicated() to identify which rows are duplicates.

• Use duplicated().sum() to count the total number of duplicate rows.

• Use drop_duplicates() to remove duplicate rows. Store the result in a new DataFrame
and display it.

• Convert the 'Score' column from string to float using astype(float).

• Convert the 'Join_Date' column to datetime format using pd.to_datetime().

• Convert the 'Passed' column to boolean type.

• Rename the column 'Student_ID' to 'ID' and 'Join_Date' to 'Enrollment_Date'
using
rename().

• Use replace() to change all 'Yes' values to 1 and all 'No' values to 0 in the Passed
column.

• Explain in 2-3 sentences: Why is data type conversion important before performing

statistical analysis?

In [8]:
df = pd.DataFrame({
    'Student_ID': ['S001', 'S002', 'S003', 'S001', 'S004', 'S002'],
    'Join_Date': ['2023-01-15', '2023-02-20', '2023-03-10',
                  '2023-01-15', '2023-04-05', '2023-02-20'],
    'Score': ['85.5', '78.0', '92.3', '85.5', '88.1', '78.0'],
    'Passed': ['Yes', 'No', 'Yes', 'Yes', 'Yes', 'No']
})

df.to_csv('cleaning_data.csv', index=False)

df = pd.read_csv('cleaning_data.csv')
df

  Student_ID   Join_Date  Score Passed
0       S001  2023-01-15   85.5    Yes
1       S002  2023-02-20   78.0     No
2       S003  2023-03-10   92.3    Yes
3       S001  2023-01-15   85.5    Yes
4       S004  2023-04-05   88.1    Yes
5       S002  2023-02-20   78.0     No

In [9]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

duplicated() gives True for rows that are exact copies of an earlier row, and False for the rest.

In [ ]:
df.duplicated().sum()

np.int64(2)

This gives the total number of duplicate rows in the DataFrame.

In [ ]:
df_no_dup = df.drop_duplicates().copy()
df_no_dup

  Student_ID   Join_Date  Score Passed
0       S001  2023-01-15   85.5    Yes
1       S002  2023-02-20   78.0     No
2       S003  2023-03-10   92.3    Yes
4       S004  2023-04-05   88.1    Yes

drop_duplicates() removes the duplicate rows and keeps only the first copy of each. The result is stored in df_no_dup.

In [ ]:
df_no_dup['Score'] = df_no_dup['Score'].astype(float)
df_no_dup.dtypes

Student_ID     object
Join_Date      object
Score         float64
Passed         object
dtype: object

This converts the Score column from text (string) to float, so it can be used in numeric calculations.

In [ ]:
df_no_dup['Join_Date'] = pd.to_datetime(df_no_dup['Join_Date'])
df_no_dup.dtypes

Student_ID            object
Join_Date     datetime64[ns]
Score                float64
Passed                object
dtype: object

pd.to_datetime() converts the Join_Date column from plain text to an actual date format, so we can do date operations on it.

In [ ]:
df_no_dup['Passed'] = df_no_dup['Passed'].map({'Yes': True, 'No': False})
df_no_dup

  Student_ID  Join_Date  Score  Passed
0       S001 2023-01-15   85.5    True
1       S002 2023-02-20   78.0   False
2       S003 2023-03-10   92.3    True
4       S004 2023-04-05   88.1    True

This converts the Passed column from Yes/No text into True/False boolean values.

In [ ]:
df_no_dup = df_no_dup.rename(columns={'Student_ID': 'ID', 'Join_Date': 'Enrollment_Date'})
df_no_dup

     ID Enrollment_Date  Score  Passed
0  S001      2023-01-15   85.5    True
1  S002      2023-02-20   78.0   False
2  S003      2023-03-10   92.3    True
4  S004      2023-04-05   88.1    True

rename() changes the column names Student_ID to ID and Join_Date to Enrollment_Date.

In [ ]:
df_no_dup['Passed'] = df_no_dup['Passed'].replace({True: 1, False: 0})
df_no_dup

     ID Enrollment_Date  Score  Passed
0  S001      2023-01-15   85.5       1
1  S002      2023-02-20   78.0       0
2  S003      2023-03-10   92.3       1
4  S004      2023-04-05   88.1       1

replace() is used to change the Yes/No style values into 1 and 0. Since Passed is already boolean here, this converts True to 1 and False to 0.

Data type conversion is important because calculations like mean, sum, or comparisons only work correctly on the right data type. If Score stays as text, we cannot do math on it, and if Join_Date stays as text, we cannot compare or sort dates properly.

## Q5. Sorting and Ranking
Create a CSV file named sorting_data.csv with student marks and attendance. Then practice
sorting rows and ranking students based on their performance.

import pandas as pd

df = pd.DataFrame({

'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'],

'Marks': [85, 78, 92, 88, 75, 91],

'Attendance': [90, 85, 95, 80, 88, 92]

})

df.to_csv('sorting_data.csv', index=False)

df = pd.read_csv('sorting_data.csv')

Perform the following tasks:

• Sort the DataFrame by the 'Marks' column in ascending order using sort_values().

• Sort the DataFrame by the 'Marks' column in descending order.

• Sort by multiple columns: first by 'Attendance' (ascending), then by 'Marks'
(descending).

• Add a new column 'Rank' that ranks students by Marks where rank 1 = highest
marks. Use rank(method='min', ascending=False).

• Add a column 'Attendance_Rank' using the dense ranking method.

• Find the top 3 students by Marks using nlargest(3, 'Marks').

• Find the bottom 2 students by Attendance using nsmallest(2, 'Attendance').

• After sorting, reset the index to default integers and drop the old index
using
reset_index(drop=True).

In [11]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'],
    'Marks': [85, 78, 92, 88, 75, 91],
    'Attendance': [90, 85, 95, 80, 88, 92]
})

df.to_csv('sorting_data.csv', index=False)

df = pd.read_csv('sorting_data.csv')
df

      Name  Marks  Attendance
0    Alice     85          90
1      Bob     78          85
2  Charlie     92          95
3    Diana     88          80
4      Eve     75          88
5    Frank     91          92

In [13]:
df.sort_values('Marks')

      Name  Marks  Attendance
4      Eve     75          88
1      Bob     78          85
0    Alice     85          90
3    Diana     88          80
5    Frank     91          92
2  Charlie     92          95

sort_values('Marks') arranges the rows from lowest to highest Marks (ascending order is the default).

In [ ]:
df.sort_values('Marks', ascending=False)

      Name  Marks  Attendance
2  Charlie     92          95
5    Frank     91          92
3    Diana     88          80
0    Alice     85          90
1      Bob     78          85
4      Eve     75          88

This sorts the rows from highest to lowest Marks by setting ascending=False.

In [ ]:
df.sort_values(['Attendance', 'Marks'], ascending=[True, False])

      Name  Marks  Attendance
3    Diana     88          80
1      Bob     78          85
4      Eve     75          88
0    Alice     85          90
5    Frank     91          92
2  Charlie     92          95

This first sorts by Attendance in ascending order. If two rows have the same Attendance, it then sorts those by Marks in descending order.

In [ ]:
df['Rank'] = df['Marks'].rank(method='min', ascending=False)
df

      Name  Marks  Attendance  Rank
0    Alice     85          90   4.0
1      Bob     78          85   5.0
2  Charlie     92          95   1.0
3    Diana     88          80   3.0
4      Eve     75          88   6.0
5    Frank     91          92   2.0

This adds a Rank column where the student with the highest Marks gets rank 1. method='min' means if two students have the same marks, they get the same (lowest) rank number.

In [ ]:
df['Attendance_Rank'] = df['Attendance'].rank(method='dense', ascending=False)
df

      Name  Marks  Attendance  Rank  Attendance_Rank
0    Alice     85          90   4.0              3.0
1      Bob     78          85   5.0              5.0
2  Charlie     92          95   1.0              1.0
3    Diana     88          80   3.0              6.0
4      Eve     75          88   6.0              4.0
5    Frank     91          92   2.0              2.0

This adds an Attendance_Rank column using dense ranking, where ranks don't skip numbers even if there is a tie.

In [ ]:
df.nlargest(3, 'Marks')

      Name  Marks  Attendance  Rank  Attendance_Rank
2  Charlie     92          95   1.0              1.0
5    Frank     91          92   2.0              2.0
3    Diana     88          80   3.0              6.0

nlargest(3, 'Marks') shows the top 3 students who have the highest Marks.

In [ ]:
df.nsmallest(2, 'Attendance')

    Name  Marks  Attendance  Rank  Attendance_Rank
3  Diana     88          80   3.0              6.0
1    Bob     78          85   5.0              5.0

nsmallest(2, 'Attendance') shows the bottom 2 students who have the lowest Attendance.

In [ ]:
df_sorted = df.sort_values('Marks', ascending=False).reset_index(drop=True)
df_sorted

      Name  Marks  Attendance  Rank  Attendance_Rank
0  Charlie     92          95   1.0              1.0
1    Frank     91          92   2.0              2.0
2    Diana     88          80   3.0              6.0
3    Alice     85          90   4.0              3.0
4      Bob     78          85   5.0              5.0
5      Eve     75          88   6.0              4.0

After sorting by Marks, reset_index(drop=True) resets the row numbers back to 0,1,2... and drops the old index instead of keeping it as a column.

## Q6. GroupBy Operations

Create a CSV file named employee_data.csv with employee records across different
departments. Then use groupby to summarize data by categories.

import pandas as pd

df = pd.DataFrame({

'Department': ['Sales', 'IT', 'Sales', 'HR', 'IT', 'HR', 'Sales', 'IT'],

'Employee': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace',
'Henry'],

'Salary': [50000, 70000, 55000, 45000, 75000, 48000, 60000, 72000],

'Experience': [2, 5, 3, 4, 6, 3, 4, 7]

})

df.to_csv('employee_data.csv', index=False)

df = pd.read_csv('employee_data.csv')

Perform the following tasks:

• Group by 'Department' and calculate the mean Salary for each department.

• Group by 'Department' and find the total Salary expenditure for each department.

• Group by 'Department' and count the number of employees in each department
using size().

• Group by 'Department' and calculate min, max, and mean of Experience using agg()
with a list.

• Group by 'Department' and apply multiple aggregations on different columns: mean
Salary and sum Experience. Use a dictionary inside agg().

• Use transform() to add a new column 'Dept_Avg_Salary' that shows the average
salary of each employee's department.

• Filter and display only those departments where the average salary is greater than
55000.

• Explain in 2-3 sentences: What is the difference between aggregation (agg) and
transformation (transform) in GroupBy?

In [ ]:
df = pd.DataFrame({
    'Department': ['Sales', 'IT', 'Sales', 'HR', 'IT', 'HR', 'Sales', 'IT'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace', 'Henry'],
    'Salary': [50000, 70000, 55000, 45000, 75000, 48000, 60000, 72000],
    'Experience': [2, 5, 3, 4, 6, 3, 4, 7]
})

df.to_csv('employee_data.csv', index=False)

df = pd.read_csv('employee_data.csv')
df

  Department Employee  Salary  Experience
0      Sales    Alice   50000           2
1         IT      Bob   70000           5
2      Sales  Charlie   55000           3
3         HR    Diana   45000           4
4         IT      Eve   75000           6
5         HR    Frank   48000           3
6      Sales    Grace   60000           4
7         IT    Henry   72000           7

In [ ]:
df.groupby('Department')['Salary'].mean()

Department
HR       46500.000000
IT       72333.333333
Sales    55000.000000
Name: Salary, dtype: float64

This groups the data by Department and finds the average Salary in each department.

In [ ]:
df.groupby('Department')['Salary'].sum()

Department
HR        93000
IT       217000
Sales    165000
Name: Salary, dtype: int64

This groups the data by Department and gives the total Salary spent in each department.

In [ ]:
df.groupby('Department').size()

Department
HR       2
IT       3
Sales    3
dtype: int64

size() counts how many employees are in each department.

In [ ]:
df.groupby('Department')['Experience'].agg(['min', 'max', 'mean'])

            min  max  mean
Department
HR            3    4   3.5
IT            5    7   6.0
Sales         2    4   3.0

This gives the minimum, maximum, and average Experience for each department using agg() with a list.

In [ ]:
df.groupby('Department').agg({'Salary': 'mean', 'Experience': 'sum'})

                  Salary  Experience
Department
HR          46500.000000           7
IT          72333.333333          18
Sales       55000.000000           9

This applies different aggregations on different columns at once: average Salary and total Experience for each department, using a dictionary inside agg().

In [ ]:
df['Dept_Avg_Salary'] = df.groupby('Department')['Salary'].transform('mean')
df

  Department Employee  Salary  Experience  Dept_Avg_Salary
0      Sales    Alice   50000           2     55000.000000
1         IT      Bob   70000           5     72333.333333
2      Sales  Charlie   55000           3     55000.000000
3         HR    Diana   45000           4     46500.000000
4         IT      Eve   75000           6     72333.333333
5         HR    Frank   48000           3     46500.000000
6      Sales    Grace   60000           4     55000.000000
7         IT    Henry   72000           7     72333.333333

transform() adds a new column that shows the department's average salary next to each employee's own row, instead of collapsing the rows like agg() does.

In [ ]:
dept_avg = df.groupby('Department')['Salary'].mean()
dept_avg[dept_avg > 55000]

Department
IT    72333.333333
Name: Salary, dtype: float64

This filters and shows only the departments whose average salary is more than 55000.

Aggregation (agg) combines all the rows of a group into a single summary value, so the number of rows becomes smaller. Transformation (transform) keeps the same number of rows as the original DataFrame, but replaces each value with a result calculated from its group, so we can attach group-level info back to every row.

## Q7. Statistical Analysis and Value Counts
Create a CSV file named product_data.csv with sales and rating information. Then calculate
various statistics and analyze value distributions.

import pandas as pd

df = pd.DataFrame({

'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A'],

'Sales': [120, 200, 150, 180, 220, 130, 190, 210, 160, 175],

'Rating': [4.2, 3.8, 4.5, 4.0, 3.9, 4.3, 4.1, 4.0, 4.4, 3.7],

'Region': ['East', 'West', 'East', 'North', 'West', 'South',

'East', 'West', 'South', 'North']

})

df.to_csv('product_data.csv', index=False)

df = pd.read_csv('product_data.csv')

Perform the following tasks:

• Calculate mean, median, and standard deviation of the Sales column.

• Calculate mean, median, and standard deviation of the Rating column.

• Find the minimum and maximum values in the Sales column.

• Calculate the 25th, 50th, and 75th percentile of Sales using quantile().

• Compute the correlation matrix for all numeric columns using corr(). Identify which
two columns are most correlated.

• Compute the covariance matrix for numeric columns using cov().

• Use value_counts() on the Product column to count how many times each product
appears.

• Use value_counts(normalize=True) on the Region column to get the percentage
distribution of each region.

• Count the number of unique values in each column using nunique().

• Calculate the range of Sales (max minus min).

In [ ]:
df = pd.DataFrame({
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A'],
    'Sales': [120, 200, 150, 180, 220, 130, 190, 210, 160, 175],
    'Rating': [4.2, 3.8, 4.5, 4.0, 3.9, 4.3, 4.1, 4.0, 4.4, 3.7],
    'Region': ['East', 'West', 'East', 'North', 'West', 'South',
               'East', 'West', 'South', 'North']
})

df.to_csv('product_data.csv', index=False)

df = pd.read_csv('product_data.csv')
df

  Product  Sales  Rating Region
0       A    120     4.2   East
1       B    200     3.8   West
2       C    150     4.5   East
3       A    180     4.0  North
4       B    220     3.9   West
5       C    130     4.3  South
6       A    190     4.1   East
7       B    210     4.0   West
8       C    160     4.4  South
9       A    175     3.7  North

In [ ]:
df['Sales'].mean(), df['Sales'].median(), df['Sales'].std()

(np.float64(173.5), 177.5, 33.33749973961588)

This gives the mean, median, and standard deviation of the Sales column.

In [ ]:
df['Rating'].mean(), df['Rating'].median(), df['Rating'].std()

(np.float64(4.09), 4.05, 0.2601281735350223)

This gives the mean, median, and standard deviation of the Rating column.

In [ ]:
df['Sales'].min(), df['Sales'].max()

(120, 220)

This gives the minimum and maximum value in the Sales column.

In [ ]:
df['Sales'].quantile([0.25, 0.5, 0.75])

0.25    152.5
0.50    177.5
0.75    197.5
Name: Sales, dtype: float64

quantile() gives the 25th, 50th, and 75th percentile of the Sales column, showing where most of the values lie.

In [ ]:
df.corr(numeric_only=True)

           Sales    Rating
Sales   1.000000 -0.636145
Rating -0.636145  1.000000

This shows the correlation matrix between Sales and Rating. The value closest to 1 or -1 shows the two columns that are most correlated (check your output and write which pair it is).

In [ ]:
df.cov(numeric_only=True)

              Sales    Rating
Sales   1111.388889 -5.516667
Rating    -5.516667  0.067667

This shows the covariance matrix, which tells how Sales and Rating change together.

In [ ]:
df['Product'].value_counts()

Product
A    4
B    3
C    3
Name: count, dtype: int64

value_counts() counts how many times each product (A, B, C) appears in the data.

In [ ]:
df['Region'].value_counts(normalize=True)

Region
East     0.3
West     0.3
North    0.2
South    0.2
Name: proportion, dtype: float64

value_counts(normalize=True) shows the percentage share of each region instead of the raw count.

In [ ]:
df.nunique()

Product     3
Sales      10
Rating      9
Region      4
dtype: int64

nunique() shows how many unique (different) values are present in each column.

In [ ]:
df['Sales'].max() - df['Sales'].min()

100

This gives the range of Sales, which is the difference between the highest and lowest sales value.

## Q8. Data Transformation: Apply, Map, and Replace
Create a CSV file named grades_data.csv with student marks and letter grades. Then
transform the data by applying custom functions and mapping values.

import pandas as pd

df = pd.DataFrame({

'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],

'Marks': [85, 78, 92, 88, 75],

'Grade_Letter': ['B', 'C', 'A', 'A', 'C']

})

df.to_csv('grades_data.csv', index=False)

df = pd.read_csv('grades_data.csv')

Perform the following tasks:

• Use apply() on the Marks column to create a new column 'Marks_Squared'
containing
the square of each mark.

• Use apply() with a lambda function to create a column 'Category' that categorizes
marks: 'High' if >= 85, 'Medium' if 70-84, 'Low' if < 70.

• Use map() on the Grade_Letter column to convert letters to grade points: A=4, B=3,
C=2, D=1, F=0. Store in a new column 'Grade_Points'.

• Use replace() to replace all occurrences of the name 'Charlie' with 'Chris' in the
Name column.

• Use apply() on the entire DataFrame to convert all string values to uppercase.

• Explain in 2-3 sentences: What is the difference between apply(), map(), and
applymap()? When should you use each one?

In [ ]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Marks': [85, 78, 92, 88, 75],
    'Grade_Letter': ['B', 'C', 'A', 'A', 'C']
})

df.to_csv('grades_data.csv', index=False)

df = pd.read_csv('grades_data.csv')
df

      Name  Marks Grade_Letter
0    Alice     85            B
1      Bob     78            C
2  Charlie     92            A
3    Diana     88            A
4      Eve     75            C

In [ ]:
df['Marks_Squared'] = df['Marks'].apply(lambda x: x ** 2)
df

      Name  Marks Grade_Letter  Marks_Squared
0    Alice     85            B           7225
1      Bob     78            C           6084
2  Charlie     92            A           8464
3    Diana     88            A           7744
4      Eve     75            C           5625

apply() runs a function on every value in the Marks column. Here it squares each mark and stores the result in a new column called Marks_Squared.

In [ ]:
df['Category'] = df['Marks'].apply(lambda x: 'High' if x >= 85 else ('Medium' if x >= 70 else 'Low'))
df

      Name  Marks Grade_Letter  Marks_Squared Category
0    Alice     85            B           7225     High
1      Bob     78            C           6084   Medium
2  Charlie     92            A           8464     High
3    Diana     88            A           7744     High
4      Eve     75            C           5625   Medium

This uses a lambda function inside apply() to label each student as High, Medium, or Low based on their Marks.

In [ ]:
grade_map = {'A': 4, 'B': 3, 'C': 2, 'D': 1, 'F': 0}
df['Grade_Points'] = df['Grade_Letter'].map(grade_map)
df

      Name  Marks Grade_Letter  Marks_Squared Category  Grade_Points
0    Alice     85            B           7225     High             3
1      Bob     78            C           6084   Medium             2
2  Charlie     92            A           8464     High             4
3    Diana     88            A           7744     High             4
4      Eve     75            C           5625   Medium             2

map() replaces each letter grade with its matching grade point using the dictionary, and stores it in a new column called Grade_Points.

In [ ]:
df['Name'] = df['Name'].replace('Charlie', 'Chris')
df

    Name  Marks Grade_Letter  Marks_Squared Category  Grade_Points
0  Alice     85            B           7225     High             3
1    Bob     78            C           6084   Medium             2
2  Chris     92            A           8464     High             4
3  Diana     88            A           7744     High             4
4    Eve     75            C           5625   Medium             2

replace() finds the name Charlie in the Name column and changes it to Chris.

In [ ]:
df.map(lambda x: x.upper() if isinstance(x, str) else x)

    Name  Marks Grade_Letter  Marks_Squared Category  Grade_Points
0  ALICE     85            B           7225     HIGH             3
1    BOB     78            C           6084   MEDIUM             2
2  CHRIS     92            A           8464     HIGH             4
3  DIANA     88            A           7744     HIGH             4
4    EVE     75            C           5625   MEDIUM             2

This applies a function to every single cell in the DataFrame. If the cell holds text, it converts it to uppercase; if it's a number, it stays unchanged.

apply() is used to run a function on a whole column or row, and is useful for calculations like squaring values or applying custom conditions. map() is used only on a single Series to replace values, often using a dictionary, like changing letter grades to points. applymap() (now called map() at DataFrame level in newer pandas) is used when we want to apply a function to every individual cell of the whole DataFrame at once.

## Q9. Merging, Joining, and Concatenating
Create three CSV files with related data, then practice combining them using merge() and
concat().

import pandas as pd

df1 = pd.DataFrame({
'ID': [1, 2, 3, 4],
'Name': ['Alice', 'Bob', 'Charlie', 'Diana']
})

df1.to_csv('employees.csv', index=False)

df2 = pd.DataFrame({

'ID': [3, 4, 5, 6],

'Salary': [50000, 60000, 70000, 80000]

})

df2.to_csv('salaries.csv', index=False)

df3 = pd.DataFrame({

'ID': [7, 8],

'Name': ['Eve', 'Frank'],

'Salary': [55000, 65000]

})

df3.to_csv('new_employees.csv', index=False)

df1 = pd.read_csv('employees.csv')

df2 = pd.read_csv('salaries.csv')

df3 = pd.read_csv('new_employees.csv')

Perform the following tasks:

• Merge df1 and df2 on the 'ID' column using an inner join (how='inner'). How
many
rows result? Explain why.

• Merge df1 and df2 on 'ID' using a left join (how='left'). Which rows are included?
Which have NaN values?

• Merge df1 and df2 on 'ID' using a right join (how='right'). Compare the result with
the left join.

• Merge df1 and df2 on 'ID' using an outer join (how='outer'). How many rows result?
Explain why outer join includes more rows.

• Concatenate df1 and df3 vertically (row-wise) using pd.concat([df1, df3], axis=0).

• Concatenate df1 and df2 horizontally (column-wise) with axis=1. What do you
observe about the alignment of rows?

• Explain in 2-3 sentences: What is the difference between merge() and concat()?
When would you use each?

• Explain in 2-3 sentences: When should you use an inner join versus an outer join
during EDA?

In [ ]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana']
})
df1.to_csv('employees.csv', index=False)

df2 = pd.DataFrame({
    'ID': [3, 4, 5, 6],
    'Salary': [50000, 60000, 70000, 80000]
})
df2.to_csv('salaries.csv', index=False)

df3 = pd.DataFrame({
    'ID': [7, 8],
    'Name': ['Eve', 'Frank'],
    'Salary': [55000, 65000]
})
df3.to_csv('new_employees.csv', index=False)

df1 = pd.read_csv('employees.csv')
df2 = pd.read_csv('salaries.csv')
df3 = pd.read_csv('new_employees.csv')

df1

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    Diana

In [ ]:
pd.merge(df1, df2, on='ID', how='inner')

   ID     Name  Salary
0   3  Charlie   50000
1   4    Diana   60000

Inner join keeps only the IDs that are present in both df1 and df2. Only ID 3 and 4 match in both, so the result has 2 rows.

In [ ]:
pd.merge(df1, df2, on='ID', how='left')

   ID     Name   Salary
0   1    Alice      NaN
1   2      Bob      NaN
2   3  Charlie  50000.0
3   4    Diana  60000.0

Left join keeps all rows from df1 (ID 1, 2, 3, 4). Since df2 does not have Salary for ID 1 and 2, those rows show NaN in the Salary column.

In [ ]:
pd.merge(df1, df2, on='ID', how='right')

   ID     Name  Salary
0   3  Charlie   50000
1   4    Diana   60000
2   5      NaN   70000
3   6      NaN   80000

Right join keeps all rows from df2 (ID 3, 4, 5, 6). Since df1 does not have Name for ID 5 and 6, those rows show NaN in the Name column. This is the opposite of the left join.

In [ ]:
pd.merge(df1, df2, on='ID', how='outer')

   ID     Name   Salary
0   1    Alice      NaN
1   2      Bob      NaN
2   3  Charlie  50000.0
3   4    Diana  60000.0
4   5      NaN  70000.0
5   6      NaN  80000.0

Outer join keeps all IDs from both df1 and df2 (1, 2, 3, 4, 5, 6), so the result has 6 rows. It includes more rows because it does not drop any ID from either side, and fills NaN wherever data is missing.

In [ ]:
pd.concat([df1, df3], axis=0)

   ID     Name   Salary
0   1    Alice      NaN
1   2      Bob      NaN
2   3  Charlie      NaN
3   4    Diana      NaN
0   7      Eve  55000.0
1   8    Frank  65000.0

This stacks df1 and df3 one below the other (row-wise). Since df1 does not have a Salary column, those rows show NaN for Salary.

In [ ]:
pd.concat([df1, df2], axis=1)

   ID     Name  ID  Salary
0   1    Alice   3   50000
1   2      Bob   4   60000
2   3  Charlie   5   70000
3   4    Diana   6   80000

This joins df1 and df2 side by side (column-wise), matching rows purely by their position, not by ID. So row 0 of df1 (ID 1) sits next to row 0 of df2 (ID 3), which does not actually mean they are related — the IDs don't line up.

merge() combines DataFrames based on matching values in a common column, like ID, similar to how tables are joined in SQL. concat() simply stacks DataFrames together, either on top of each other (rows) or side by side (columns), without checking if values match. We use merge() when we want to combine related data using a key, and concat() when we just want to add more rows or columns together.

Inner join is used during EDA when we only want to look at records that exist in both datasets, giving cleaner and complete data. Outer join is used when we want to see everything from both datasets, including unmatched records, which helps to spot missing data or gaps between the two sources.

## Q10. Pivot Tables and Cross Tabulation

Create a CSV file named sales_data.csv with sales and profit data across regions and
products. Then create pivot tables and cross-tabulations to summarize the data.

import pandas as pd

df = pd.DataFrame({

'Region': ['North', 'South', 'East', 'West', 'North',

'South', 'East', 'West', 'North', 'South'],

'Product': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B', 'B', 'A'],

'Sales': [200, 150, 300, 250, 180, 220, 280, 260, 190, 210],

'Profit': [50, 30, 80, 60, 45, 55, 70, 65, 40, 52]

})

df.to_csv('sales_data.csv', index=False)

df = pd.read_csv('sales_data.csv')

Perform the following tasks:

• Create a pivot table showing the average Sales by Region (rows) and Product
(columns).

• Create a pivot table showing the total Profit by Region (rows) and Product (columns).

• Create a pivot table with multiple aggregations: mean Sales and sum Profit, grouped
by Region.

• Use pd.crosstab() to create a frequency table showing the count of each Product for
each Region.

• Use pd.crosstab() with normalize=True to show proportions instead of raw counts.

• Add margins=True to the crosstab to display row totals and column totals.

• Explain in 2-3 sentences: When is pivot_table() more useful than groupby() in EDA?

• Explain in 2-3 sentences: What is the difference between a pivot table and a
cross-tabulation (crosstab)?

In [ ]:
df = pd.DataFrame({
    'Region': ['North', 'South', 'East', 'West', 'North',
               'South', 'East', 'West', 'North', 'South'],
    'Product': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B', 'B', 'A'],
    'Sales': [200, 150, 300, 250, 180, 220, 280, 260, 190, 210],
    'Profit': [50, 30, 80, 60, 45, 55, 70, 65, 40, 52]
})

df.to_csv('sales_data.csv', index=False)

df = pd.read_csv('sales_data.csv')
df

  Region Product  Sales  Profit
0  North       A    200      50
1  South       A    150      30
2   East       B    300      80
3   West       B    250      60
4  North       A    180      45
5  South       B    220      55
6   East       A    280      70
7   West       B    260      65
8  North       B    190      40
9  South       A    210      52

In [ ]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='mean')

Product      A      B
Region
East     280.0  300.0
North    190.0  190.0
South    180.0  220.0
West       NaN  255.0

This pivot table shows the average Sales for each Region and Product combination.

In [ ]:
pd.pivot_table(df, values='Profit', index='Region', columns='Product', aggfunc='sum')

Product     A      B
Region
East     70.0   80.0
North    95.0   40.0
South    82.0   55.0
West      NaN  125.0

This pivot table shows the total Profit for each Region and Product combination.

In [ ]:
pd.pivot_table(df, index='Region', values=['Sales', 'Profit'], aggfunc={'Sales': 'mean', 'Profit': 'sum'})

        Profit       Sales
Region
East       150  290.000000
North      135  190.000000
South      137  193.333333
West       125  255.000000

This pivot table shows two things at once: average Sales and total Profit, grouped by Region.

In [ ]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B
Region
East     1  1
North    2  1
South    2  1
West     0  2

crosstab() shows how many times each Product appears in each Region, like a frequency count table.

In [ ]:
pd.crosstab(df['Region'], df['Product'], normalize=True)

Product    A    B
Region
East     0.1  0.1
North    0.2  0.1
South    0.2  0.1
West     0.0  0.2

normalize=True changes the counts into proportions (out of 1), so we see the percentage share instead of raw numbers.

In [ ]:
pd.crosstab(df['Region'], df['Product'], margins=True)

Product  A  B  All
Region
East     1  1    2
North    2  1    3
South    2  1    3
West     0  2    2
All      5  5   10

margins=True adds an extra row and column showing the total count for each Region and each Product, along with the grand total.

pivot_table() is more useful than groupby() when we want to arrange data in a table format with one variable as rows and another as columns, making it easier to compare combinations at a glance, especially for two categorical variables at once.

A pivot table can perform different aggregations like mean, sum, or count on a numeric column, and gives full control over how data is summarized. A cross-tabulation (crosstab) is mainly used to count the frequency of combinations between two categorical columns, and by default it only counts occurrences rather than summarizing a numeric column.